version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: depotiq-postgres
    environment:
      POSTGRES_USER: depotiq_user
      POSTGRES_PASSWORD: depotiq_password_secret
      POSTGRES_DB: depotiq_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
