CREATE TABLE user_settings (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    default_horizon INTEGER NOT NULL DEFAULT 7,
    safety_stock_days INTEGER NOT NULL DEFAULT 3,
    alert_threshold INTEGER NOT NULL DEFAULT 250,
    auto_refresh BOOLEAN NOT NULL DEFAULT TRUE,
    require_approval BOOLEAN NOT NULL DEFAULT TRUE,
    allow_overrides BOOLEAN NOT NULL DEFAULT TRUE,
    email_alerts BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
