import { PackageSearch, PencilLine, Plus, Search, Tags, Trash2, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { createProduct, deleteProduct, loadProducts, updateProduct } from "../api/depotiqApi.js";
import AppSidebar from "../components/AppSidebar.jsx";

const money = (value) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value ?? 0));
const EMPTY_PRODUCT = { productCode: "", name: "", category: "", brand: "", supplierCode: "", unitCost: 0, price: 0, weightKg: 0, shelfLifeDays: 0, perishable: false };

export default function ProductsView({ collapsed, onAction, onCollapse, onNavigate, onSignOut, permissions, user }) {
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [query, setQuery] = useState("");
  const [formOpen, setFormOpen] = useState(false), [editing, setEditing] = useState(null), [form, setForm] = useState(EMPTY_PRODUCT), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { setError(""); setProducts(await loadProducts()); } catch (e) { setError(e.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const visible = useMemo(() => { const q = query.toLowerCase().trim(); return !q ? products : products.filter((p) => [p.productCode, p.name, p.category, p.brand].some((v) => String(v ?? "").toLowerCase().includes(q))); }, [products, query]);
  const setField = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const openForm = (product = null) => { setEditing(product); setForm(product ? { ...product } : EMPTY_PRODUCT); setFormOpen(true); };
  const save = async (event) => { event.preventDefault(); setSaving(true); try { const payload = { ...form, unitCost: Number(form.unitCost), price: Number(form.price), weightKg: Number(form.weightKg), shelfLifeDays: Number(form.shelfLifeDays) }; const saved = editing ? await updateProduct(editing.id, (({ productCode, ...value }) => value)(payload)) : await createProduct(payload); setProducts((current) => editing ? current.map((p) => p.id === saved.id ? saved : p) : [...current, saved]); setFormOpen(false); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const remove = async (product) => { if (!globalThis.confirm(`Delete ${product.productCode}?`)) return; try { await deleteProduct(product.id); setProducts((current) => current.filter((p) => p.id !== product.id)); } catch (e) { setError(e.message); } };
  return <div className={collapsed ? "app-shell sidebar-collapsed" : "app-shell"}>
    <AppSidebar activePage="Products" collapsed={collapsed} onAction={onAction} onCollapse={onCollapse} onNavigate={onNavigate} onSignOut={onSignOut} permissions={permissions} user={user} />
    <main className="dashboard products-page"><header className="topbar"><h1>Products</h1><label className="search-box"><Search size={15} /><span className="sr-only">Search products</span><input onChange={(e) => setQuery(e.target.value)} placeholder="Search product, code, category, or brand..." value={query} /></label></header>
      {error && <div className="notice error">{error}</div>}
      <section className="metrics-grid"><article className="metric-card"><PackageSearch size={20} /><div><span>Total Products</span><strong>{products.length}</strong><small>In product catalog</small></div></article><article className="metric-card"><Tags size={20} /><div><span>Categories</span><strong>{new Set(products.map((p) => p.category)).size}</strong><small>Product groups</small></div></article></section>
      <section className="table-panel products-table-panel"><div className="panel-toolbar"><h2>Product catalog</h2><div className="table-actions"><span>{visible.length} shown</span><button className="tool-button" onClick={() => openForm()} type="button"><Plus size={14} />Add product</button></div></div><div className="table-scroll"><table><thead><tr><th>Code</th><th>Product</th><th>Category</th><th>Brand</th><th>Supplier</th><th>Price</th><th>Perishable</th><th>Actions</th></tr></thead><tbody>{visible.map((p) => <tr key={p.id}><td>{p.productCode}</td><td>{p.name}</td><td>{p.category}</td><td>{p.brand || "—"}</td><td>{p.supplierCode || "—"}</td><td>{money(p.price)}</td><td>{p.perishable ? "Yes" : "No"}</td><td><div className="action-buttons"><button className="icon-button" onClick={() => openForm(p)} type="button"><PencilLine size={14} /></button><button className="reject-button" onClick={() => remove(p)} type="button"><Trash2 size={14} /></button></div></td></tr>)}</tbody></table></div>{loading && <div className="panel-empty">Loading products...</div>}{!loading && !visible.length && <div className="panel-empty">No products match your search.</div>}</section>
    </main>{formOpen && <div className="modal-backdrop"><section className="override-dialog store-form-dialog" role="dialog"><header><div><span>Product catalog</span><h2>{editing ? "Edit product" : "Add product"}</h2></div><button className="icon-button" onClick={() => setFormOpen(false)} type="button"><X size={16} /></button></header><form onSubmit={save}>{[["productCode","Product code"],["name","Name"],["category","Category"],["brand","Brand"],["supplierCode","Supplier code"],["unitCost","Unit cost"],["price","Price"],["weightKg","Weight (kg)"],["shelfLifeDays","Shelf life (days)"]].map(([key,label]) => <label key={key}>{label}<input disabled={editing && key === "productCode"} onChange={(e) => setField(key,e.target.value)} required={["productCode","name","category"].includes(key)} type={["unitCost","price","weightKg","shelfLifeDays"].includes(key) ? "number" : "text"} value={form[key] ?? ""} /></label>)}<label className="checkbox-field"><input checked={form.perishable} onChange={(e) => setField("perishable",e.target.checked)} type="checkbox" />Perishable</label><footer><button className="secondary-button" onClick={() => setFormOpen(false)} type="button">Cancel</button><button className="save-button" disabled={saving} type="submit">{saving ? "Saving..." : "Save product"}</button></footer></form></section></div>}</div>;
}
