import { Boxes, CircleAlert, PencilLine, Search, Store, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { loadStoreInventory, updateStoreInventory } from "../api/depotiqApi.js";
import AppSidebar from "../components/AppSidebar.jsx";
import ProfileMenu from "../components/ProfileMenu.jsx";

const number = (value) => new Intl.NumberFormat("en-US").format(Number(value ?? 0));
const state = (item) => Number(item.inventoryLevel ?? 0) === 0 ? "OUT" : Number(item.inventoryLevel ?? 0) < 25 ? "LOW" : "HEALTHY";

export default function StoreInventoryView({ collapsed, onAction, onCollapse, onNavigate, onSignOut, permissions, user }) {
  const [inventory, setInventory] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(""), [query, setQuery] = useState("");
  const [editing, setEditing] = useState(null), [inventoryLevel, setInventoryLevel] = useState(""), [incomingUnits, setIncomingUnits] = useState(""), [saving, setSaving] = useState(false), [message, setMessage] = useState("");
  const load = useCallback(async () => { try { setError(""); setInventory(await loadStoreInventory()); } catch (e) { setError(e.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const visible = useMemo(() => { const q = query.toLowerCase().trim(); return !q ? inventory : inventory.filter((item) => [item.storeCode,item.storeName,item.productCode,item.productName,item.category].some((value) => String(value ?? "").toLowerCase().includes(q))); }, [inventory, query]);
  const atRisk = inventory.filter((item) => state(item) !== "HEALTHY").length;
  const openEdit = (item) => { setEditing(item); setInventoryLevel(String(item.inventoryLevel)); setIncomingUnits(String(item.incomingUnits)); setError(""); };
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const updated = await updateStoreInventory({ storeId: editing.storeId, productId: editing.productId, inventoryLevel: Number(inventoryLevel), incomingUnits: Number(incomingUnits) }); setInventory((current) => current.map((item) => item.id === updated.id ? updated : item)); setEditing(null); setMessage(`${updated.storeCode} / ${updated.productCode} inventory was updated.`); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  return <div className={collapsed ? "app-shell sidebar-collapsed" : "app-shell"}><AppSidebar activePage="Store Inventory" collapsed={collapsed} onAction={onAction} onCollapse={onCollapse} onNavigate={onNavigate} onSignOut={onSignOut} permissions={permissions} user={user} />
    <main className="dashboard store-inventory-page"><header className="topbar"><h1>Store Inventory</h1><label className="search-box"><Search size={15} /><span className="sr-only">Search store inventory</span><input onChange={(event) => setQuery(event.target.value)} placeholder="Search store, product, or category..." value={query} /></label><ProfileMenu onSignOut={onSignOut} user={user} /></header>
      {(error || message) && <div className={error ? "notice error" : "notice"}>{error || message}</div>}
      <section className="metrics-grid"><article className="metric-card"><Boxes size={20} /><div><span>Inventory Records</span><strong>{inventory.length}</strong><small>Store-product stock levels</small></div></article><article className="metric-card"><CircleAlert size={20} /><div><span>Stock Alerts</span><strong>{atRisk}</strong><small>Low or out of stock</small></div></article><article className="metric-card"><Store size={20} /><div><span>Stores Covered</span><strong>{new Set(inventory.map((item) => item.storeId)).size}</strong><small>Inventory locations</small></div></article></section>
      <section className="table-panel"><div className="panel-toolbar"><h2>Store stock levels</h2><span>{visible.length} shown</span></div><div className="table-scroll"><table><thead><tr><th>Store</th><th>Product</th><th>Category</th><th>On hand</th><th>Incoming</th><th>Status</th><th>Updated</th>{permissions.canManageInventory && <th>Action</th>}</tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td>{item.storeCode}</td><td>{item.productCode}</td><td>{item.category}</td><td>{number(item.inventoryLevel)}</td><td>{number(item.incomingUnits)}</td><td><span className={`priority ${state(item).toLowerCase()}`}>{state(item)}</span></td><td>{item.lastUpdated ? new Date(item.lastUpdated).toLocaleDateString() : "—"}</td>{permissions.canManageInventory && <td><button aria-label={`Edit ${item.storeCode} ${item.productCode} inventory`} className="icon-button" onClick={() => openEdit(item)} type="button"><PencilLine size={14} /></button></td>}</tr>)}</tbody></table></div>{loading && <div className="panel-empty">Loading store inventory...</div>}{!loading && !visible.length && <div className="panel-empty">No inventory records match your search.</div>}</section>
    </main>{editing && <div className="modal-backdrop"><section className="override-dialog" role="dialog"><header><div><span>Store inventory</span><h2>Adjust stock levels</h2></div><button className="icon-button" disabled={saving} onClick={() => setEditing(null)} type="button"><X size={16} /></button></header><p>{editing.storeCode} / {editing.productCode}</p><form onSubmit={save}><label>On-hand units<input min="0" onChange={(event) => setInventoryLevel(event.target.value)} required type="number" value={inventoryLevel} /></label><label>Incoming units<input min="0" onChange={(event) => setIncomingUnits(event.target.value)} required type="number" value={incomingUnits} /></label><footer><button className="secondary-button" disabled={saving} onClick={() => setEditing(null)} type="button">Cancel</button><button className="save-button" disabled={saving} type="submit">{saving ? "Saving..." : "Save inventory"}</button></footer></form></section></div>}</div>;
}
