import { Boxes, CircleAlert, PencilLine, Search, Store, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { loadStoreInventory, updateStoreInventory } from "../api/depotiqApi.js";
import AppSidebar from "../components/AppSidebar.jsx";
import UserAvatar from "../components/UserAvatar.jsx";

const number = (value) => new Intl.NumberFormat("en-US").format(Number(value ?? 0));
function stockState(item) {
  const value = Number(item.inventoryLevel ?? 0);
  if (value === 0) return { key: "out", label: "Out of stock" };
  if (value < 25) return { key: "low", label: "Low stock" };
  return { key: "in", label: "In stock" };
}

export default function StoreInventoryView({ collapsed, onAction, onCollapse, onNavigate, onSignOut, permissions, profile, user }) {
  const [inventory, setInventory] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(""), [message, setMessage] = useState("");
  const [query, setQuery] = useState(""), [storeFilter, setStoreFilter] = useState("ALL"), [statusFilter, setStatusFilter] = useState("ALL");
  const [editing, setEditing] = useState(null), [inventoryLevel, setInventoryLevel] = useState(""), [incomingUnits, setIncomingUnits] = useState(""), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { setError(""); setInventory(await loadStoreInventory()); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const visible = useMemo(() => { const normalized = query.toLowerCase().trim(); return inventory.filter((item) => storeFilter === "ALL" || item.storeCode === storeFilter).filter((item) => statusFilter === "ALL" || stockState(item).key === statusFilter).filter((item) => !normalized || [item.storeCode, item.storeName, item.productCode, item.productName, item.category].some((value) => String(value ?? "").toLowerCase().includes(normalized))); }, [inventory, query, statusFilter, storeFilter]);
  const storeOptions = [...new Set(inventory.map((item) => item.storeCode))].sort();
  const atRisk = inventory.filter((item) => stockState(item).key !== "in").length;
  const openEdit = (item) => { setEditing(item); setInventoryLevel(String(item.inventoryLevel)); setIncomingUnits(String(item.incomingUnits)); setError(""); };
  const closeEdit = () => { if (!saving) setEditing(null); };
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const updated = await updateStoreInventory({ storeId: editing.storeId, productId: editing.productId, inventoryLevel: Number(inventoryLevel), incomingUnits: Number(incomingUnits) }); setInventory((current) => current.map((item) => item.id === updated.id ? updated : item)); setEditing(null); setMessage(`${updated.storeCode} / ${updated.productCode} inventory was updated.`); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };

  return <div className={collapsed ? "app-shell sidebar-collapsed" : "app-shell"}>
    <AppSidebar activePage="Store Inventory" collapsed={collapsed} onAction={onAction} onCollapse={onCollapse} onNavigate={onNavigate} onSignOut={onSignOut} permissions={permissions} profile={profile} user={user} />
    <main className="dashboard store-inventory-page">
      <header className="topbar"><h1>Store Inventory</h1><label className="search-box"><Search size={15} /><span className="sr-only">Search store inventory</span><input onChange={(event) => setQuery(event.target.value)} placeholder="Search store, product, or category..." value={query} /></label><UserAvatar onClick={() => onNavigate("Profile")} profile={profile} user={user} /></header>
      {(error || message) && <div className={error ? "notice error" : "notice"}>{error || message}</div>}
      <section className="metrics-grid"><article className="metric-card"><Boxes size={20} /><div><span>Inventory Records</span><strong>{inventory.length}</strong><small>Store-product stock levels</small></div></article><article className="metric-card"><CircleAlert size={20} /><div><span>Stock Alerts</span><strong>{atRisk}</strong><small>Low or out of stock</small></div></article><article className="metric-card"><Store size={20} /><div><span>Stores Covered</span><strong>{new Set(inventory.map((item) => item.storeId)).size}</strong><small>Inventory locations</small></div></article></section>
      <section className="table-panel store-inventory-table"><div className="panel-toolbar inventory-page-toolbar"><h2>Store stock levels</h2><div className="inventory-page-filters"><label><span>Store</span><select onChange={(event) => setStoreFilter(event.target.value)} value={storeFilter}><option value="ALL">All stores</option>{storeOptions.map((code) => <option key={code}>{code}</option>)}</select></label><label><span>Stock status</span><select onChange={(event) => setStatusFilter(event.target.value)} value={statusFilter}><option value="ALL">All statuses</option><option value="out">Out of stock</option><option value="low">Low stock</option><option value="in">In stock</option></select></label></div></div><div className="table-scroll"><table><thead><tr><th>Store</th><th>Product</th><th>Category</th><th>On hand</th><th>Incoming</th><th>Available soon</th><th>Status</th><th>Updated</th>{permissions.canManageInventory && <th>Action</th>}</tr></thead><tbody>{visible.map((item) => { const status = stockState(item); return <tr key={item.id}><td><div className="table-primary"><strong>{item.storeCode}</strong><span>{item.storeName}</span></div></td><td><div className="table-primary"><strong>{item.productCode}</strong><span>{item.productName}</span></div></td><td>{item.category}</td><td>{number(item.inventoryLevel)}</td><td>{number(item.incomingUnits)}</td><td>{number(Number(item.inventoryLevel) + Number(item.incomingUnits))}</td><td><span className={`inventory-health ${status.key}`}><i />{status.label}</span></td><td>{item.lastUpdated ? new Date(item.lastUpdated).toLocaleDateString() : "—"}</td>{permissions.canManageInventory && <td><button aria-label={`Edit ${item.storeCode} ${item.productCode} inventory`} className="icon-button" onClick={() => openEdit(item)} type="button"><PencilLine size={14} /></button></td>}</tr>; })}</tbody></table></div>{loading && <div className="panel-empty">Loading store inventory...</div>}{!loading && !visible.length && <div className="panel-empty">No inventory records match these filters.</div>}</section>
    </main>
    {editing && <div className="modal-backdrop" onClick={(event) => { if (event.target === event.currentTarget) closeEdit(); }}><section aria-modal="true" className="override-dialog inventory-adjust-dialog" role="dialog"><header><div><span>Store inventory</span><h2>Adjust stock levels</h2></div><button aria-label="Close inventory dialog" className="icon-button" disabled={saving} onClick={closeEdit} type="button"><X size={16} /></button></header><p>{editing.storeCode} / {editing.productCode}</p><form onSubmit={save}><div className="dialog-field-grid"><label>On-hand units<input min="0" onChange={(event) => setInventoryLevel(event.target.value)} required type="number" value={inventoryLevel} /></label><label>Incoming units<input min="0" onChange={(event) => setIncomingUnits(event.target.value)} required type="number" value={incomingUnits} /></label></div><div className="inventory-total-preview"><span>Available after delivery</span><strong>{number(Number(inventoryLevel || 0) + Number(incomingUnits || 0))}</strong></div><footer><button className="secondary-button" disabled={saving} onClick={closeEdit} type="button">Cancel</button><button className="save-button" disabled={saving} type="submit">{saving ? "Saving..." : "Save inventory"}</button></footer></form></section></div>}
  </div>;
}
